services:
  fe-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mangarec-fe-service:dev
    container_name: fe-service-dev
    ports:
      - "${FE_PORT:-3000}:3000"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8080}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID:-264778620233-r8k76djk9hqtcu9b0of9bqrgfd7kjcng.apps.googleusercontent.com}
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - mangarec-network
    volumes:
      - .:/app
      - fe_node_modules:/app/node_modules
    command: npm run dev

networks:
  mangarec-network:
    name: mangarec_global_network
    external: true

volumes:
  fe_node_modules:
