services:
  be-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: be-service-dev
    ports:
      - "8080:8080"
    networks:
      - mangarec-network
    env_file: .env
    volumes:
      # Mount entire source code for hot-reloading
      - .:/app
    # command: ... (Depends on tech stack, e.g., npm run dev, or spring-boot:run)

  postgres:
    image: postgres:15-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: mangarec_be
    networks:
      - mangarec-network
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  mangarec-network:
    name: mangarec_global_network
    external: true

volumes:
  pg_data_dev:
