"""Add EtlCheckpoint model

Revision ID: 18713387e18c
Revises: 4ddcefd52021
Create Date: 2026-06-13 15:23:51.229915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18713387e18c'
down_revision: Union[str, Sequence[str], None] = '4ddcefd52021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('last_offset', sa.Integer(), nullable=False),
    sa.Column('total_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_checkpoints_job_name'), 'etl_checkpoints', ['job_name'], unique=True)
    op.drop_table('test_persist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_persist',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_etl_checkpoints_job_name'), table_name='etl_checkpoints')
    op.drop_table('etl_checkpoints')
    # ### end Alembic commands ###
