"""Init tables

Revision ID: 4ddcefd52021
Revises: 
Create Date: 2026-06-08 11:42:33.958495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddcefd52021'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mangas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title_main', sa.String(), nullable=False),
    sa.Column('title_original', sa.String(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_vi', sa.Text(), nullable=True),
    sa.Column('demographic', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content_rating', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('rating_bayesian', sa.Float(), nullable=True),
    sa.Column('rating_average', sa.Float(), nullable=True),
    sa.Column('follows', sa.Integer(), nullable=True),
    sa.Column('has_en_translation', sa.Boolean(), nullable=False),
    sa.Column('has_vi_translation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mangas_content_rating'), 'mangas', ['content_rating'], unique=False)
    op.create_index(op.f('ix_mangas_demographic'), 'mangas', ['demographic'], unique=False)
    op.create_index(op.f('ix_mangas_follows'), 'mangas', ['follows'], unique=False)
    op.create_index(op.f('ix_mangas_rating_bayesian'), 'mangas', ['rating_bayesian'], unique=False)
    op.create_index(op.f('ix_mangas_status'), 'mangas', ['status'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('group_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_group_type'), 'tags', ['group_type'], unique=False)
    op.create_table('manga_alt_titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manga_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_alt_titles_manga_id'), 'manga_alt_titles', ['manga_id'], unique=False)
    op.create_table('manga_authors',
    sa.Column('manga_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.PrimaryKeyConstraint('manga_id', 'author_id', 'role')
    )
    op.create_table('manga_tags',
    sa.Column('manga_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('manga_id', 'tag_id')
    )
    op.create_table('related_mangas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manga_id', sa.String(), nullable=False),
    sa.Column('related_manga_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.ForeignKeyConstraint(['related_manga_id'], ['mangas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_mangas_manga_id'), 'related_mangas', ['manga_id'], unique=False)
    op.create_index(op.f('ix_related_mangas_related_manga_id'), 'related_mangas', ['related_manga_id'], unique=False)
    op.drop_table('test_persist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_persist',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_related_mangas_related_manga_id'), table_name='related_mangas')
    op.drop_index(op.f('ix_related_mangas_manga_id'), table_name='related_mangas')
    op.drop_table('related_mangas')
    op.drop_table('manga_tags')
    op.drop_table('manga_authors')
    op.drop_index(op.f('ix_manga_alt_titles_manga_id'), table_name='manga_alt_titles')
    op.drop_table('manga_alt_titles')
    op.drop_index(op.f('ix_tags_group_type'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_mangas_status'), table_name='mangas')
    op.drop_index(op.f('ix_mangas_rating_bayesian'), table_name='mangas')
    op.drop_index(op.f('ix_mangas_follows'), table_name='mangas')
    op.drop_index(op.f('ix_mangas_demographic'), table_name='mangas')
    op.drop_index(op.f('ix_mangas_content_rating'), table_name='mangas')
    op.drop_table('mangas')
    op.drop_table('authors')
    # ### end Alembic commands ###
